### ISSUE TITLE
Connector incompatibility

### ISSUE THREAD

**Issue by 3dEADto2** [nvb-uy/Item_Obliterator#6] opened 2023-09-25 04:22 UTC
Hey,

i have a simple config but it does not work. 
My config: `{
  "blacklisted_items": [
    "//Items here will be unusable completely",
    "artifacts:everlasting_beef",
    "artifacts:eternal_steak",
    "artifacts:crystal_heart",
    "things:moss_necklace"
  ],
  "only_disable_interactions": [
    "//Items here will not be able to be right-clicked (Interact)",
    "examplemod:example_item"
  ],
  "only_disable_attacks": [
    "//Items here will not be able to be used to attack",
    "examplemod:example_item"
  ]
}`.

Could it be that another mod is overwriting obliterator? Should I send my log/modlist, would that help find the error? Or any other idea what could cause the mod not to work at all?

**Comment by ImpulsiveLad** [comment] 2023-09-29 05:17
This is mine

{
  "blacklisted_items": [
    "//Items here will be unusable completely",
    "farmersdelight:rope",
    "farmersdelight:safety_net"
  ],
  "only_disable_interactions": [
    "farmersdelight:rope",
    "farmersdelight:safety_net"
  ],
  "only_disable_attacks": [
    "farmersdelight:rope",
    "farmersdelight:safety_net"
  ]
}

Don't understand if I'm doing it right or not. The mod page doesn't give adequate instructions.

Leaving in the instructons in the config causing the game to be unrunable but running my config like this does not change anything.

**Comment by nvb-uy** [comment] 2023-09-29 05:19
This might be a mod incompatibility, I'll investigate it

**Comment by ImpulsiveLad** [comment] 2023-09-29 05:23
So whose config is right?
How should it look?

**Comment by nvb-uy** [comment] 2023-09-29 05:28
> This is mine
> 
> { "blacklisted_items": [ "//Items here will be unusable completely", "farmersdelight:rope", "farmersdelight:safety_net" ], "only_disable_interactions": [ "farmersdelight:rope", "farmersdelight:safety_net" ], "only_disable_attacks": [ "farmersdelight:rope", "farmersdelight:safety_net" ] }
> 
> Don't understand if I'm doing it right or not. The mod page doesn't give adequate instructions.
> 
> Leaving in the instructons in the config causing the game to be unrunable but running my config like this does not change anything.

Have you tried removing it from the disable only interactions and attacks? If an item is disabled you won't be able to attack and interact anyway

Can't reproduce in Prominence II [FABRIC], as seen in [this video](https://cdn.discordapp.com/attachments/886303970493083780/1157186237199814686/Base_Profile_2023.09.29_-_02.23.55.06.mp4)
Using [this config](https://cdn.discordapp.com/attachments/886303970493083780/1157186343944863785/image.png)

**Comment by ImpulsiveLad** [comment] 2023-09-29 05:38
Ok I have noticed that the mod does not work if you leave in the $$ instructions below the blacklisted items list

**Comment by ImpulsiveLad** [comment] 2023-09-29 05:43
tried a bunch of things, added connector extras, purged the .connector files. I really have no idea, maybe its a incompatiblity? 
![Screenshot 2023-09-29 014244](https://github.com/nvb-uy/Item_Obliterator/assets/92990441/45c1c4a6-349a-4b39-9433-23d6316640a2)

**Comment by nvb-uy** [comment] 2023-09-29 05:51
Connector? This is a fabric mod, I have not tested connector support so it's not guaranteed.

**Comment by nvb-uy** [comment] 2023-09-29 05:53
> Hey,
> 
> i have a simple config but it does not work. My config: `{ "blacklisted_items": [ "//Items here will be unusable completely", "artifacts:everlasting_beef", "artifacts:eternal_steak", "artifacts:crystal_heart", "things:moss_necklace" ], "only_disable_interactions": [ "//Items here will not be able to be right-clicked (Interact)", "examplemod:example_item" ], "only_disable_attacks": [ "//Items here will not be able to be used to attack", "examplemod:example_item" ] }`.
> 
> Could it be that another mod is overwriting obliterator? Should I send my log/modlist, would that help find the error? Or any other idea what could cause the mod not to work at all?

Give me your logs as I'm suspecting you're also using connector, as everything seems to be fine.

**Comment by nvb-uy** [comment] 2023-09-29 06:00
> This is mine
> 
> { "blacklisted_items": [ "//Items here will be unusable completely", "farmersdelight:rope", "farmersdelight:safety_net" ], "only_disable_interactions": [ "farmersdelight:rope", "farmersdelight:safety_net" ], "only_disable_attacks": [ "farmersdelight:rope", "farmersdelight:safety_net" ] }
> 
> Don't understand if I'm doing it right or not. The mod page doesn't give adequate instructions.
> 
> Leaving in the instructons in the config causing the game to be unrunable but running my config like this does not change anything.

Next time you post an issue, please say if you're using connector. The modpage says Fabric, and it does include adequate instructions, in the "Example Configuration" section.

**Comment by ImpulsiveLad** [comment] 2023-09-29 06:02
fair fair, shouldn't make a difference however

**Comment by nvb-uy** [comment] 2023-09-29 06:03
> fair fair, shouldn't make a difference however

Yes it definetly does make a difference. This is a fabric mod, not a forge one. Connector isn't stable enough and if you read their modpage, it's on alpha, it has crashes with lots of mods, incompatibilities, etc.

**Comment by ImpulsiveLad** [comment] 2023-09-29 06:06
You did state the mod runs on connector on the mod page right?

**Comment by nvb-uy** [comment] 2023-09-29 06:09
Oh yeah, I just saw, that's my bad then, I honestly don't remember adding that. Still in the future when you open issues you should at least mention the platform

**Comment by ImpulsiveLad** [comment] 2023-09-29 06:15
Yeah, didn't open the thread and wasn't expecting a dev to respond, nvm in 2 mins lol

**Comment by 3dEADto2** [comment] 2023-10-02 19:09
> > Hey,
> > i have a simple config but it does not work. My config: `{ "blacklisted_items": [ "//Items here will be unusable completely", "artifacts:everlasting_beef", "artifacts:eternal_steak", "artifacts:crystal_heart", "things:moss_necklace" ], "only_disable_interactions": [ "//Items here will not be able to be right-clicked (Interact)", "examplemod:example_item" ], "only_disable_attacks": [ "//Items here will not be able to be used to attack", "examplemod:example_item" ] }`.
> > Could it be that another mod is overwriting obliterator? Should I send my log/modlist, would that help find the error? Or any other idea what could cause the mod not to work at all?
> 
> Give me your logs as I'm suspecting you're also using connector, as everything seems to be fine.

That is my latest log: https://pastebin.com/nqgRuw1k

**Comment by nvb-uy** [comment] 2023-10-31 07:51
Won't fix, direct forge port is being worked on

**Closed by nvb-uy** 2023-10-31 07:51 UTC
