### ISSUE TITLE
Villager trades bypass some items being uncraftable

### ISSUE THREAD

**Issue by CallMeQuinny** [nvb-uy/Item_Obliterator#68] opened 2024-09-02 18:13 UTC
While I can remove the crafting recipe for items I want removed, I see no way of removing villager trades in the config and every other removal type is in the config but not villager trading. Yet its on the modrinth page, anyone else have this same problem?

#58 same problem no one seems to have solved it yet
![image_2024-09-02_130553083](https://github.com/user-attachments/assets/6230a6cb-18c8-4ec2-95af-58aed3bebb7f)
![2024-09-02_13 10 57](https://github.com/user-attachments/assets/fb3fe2da-b3b5-4942-923e-76161c5fe816)

**Comment by CallMeQuinny** [comment] 2024-09-02 18:14
To give context i banned all diamond armor

**Comment by nvb-uy** [comment] 2024-10-13 05:04
Duplicate of https://github.com/nvb-uy/Item_Obliterator/issues/58

Will look into it

**Closed by nvb-uy** 2024-10-13 05:04 UTC
